"use client";

import React, { useState } from "react";
import { useSession } from "next-auth/react";
import Search from "./Search";
import BatchFilter from "./Inventory/batches/BatchFilter";
import AddProductForm from "./Inventory/products/AddProductform";
import ProductFilter from "./Inventory/products/ProductFilter";
import TransactionFilter from "./transaction/TransactionFilter";
import AuditFilter from "./auditLog/AuditFilter";
import ArchiveFilter from "./archive/ArchiveFilter";

import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { DateRangeFilter } from "./DateRangeFilter";
import { useRouter, useSearchParams } from "next/navigation";
import { format } from "date-fns";

interface PageTableHeaderProps {
  title: string;
  hasAddProduct?: boolean;
  isProductFilter?: boolean;
  isTransactionFilter?: boolean;
  isBatchFilter?: boolean;
  isArchiveFilter?: boolean;
  productExport?: boolean;
  batchExport?: boolean;
  transactionExport?: boolean;
  hasDateFilter?: boolean;
}

type ProductRow = {
  product_name: string;
  category?: { name: string } | null;
  totalQty?: number;
  batchNumber?: number;
  quantity?: number;
  releaseDate?: string | null;
  expiryDate?: string | null;
  product?: {
    product_name: string;
    category?: { name: string } | null;
  };
  batches?: { quantity: number }[];
};

type TransactionRow = {
  id: string;
  customer: string;
  source: "Walk In" | "Request Order";
  createdAt: string | Date;
  quantity: number;
  total: number;
  status: string;
};

const PageTableHeader: React.FC<PageTableHeaderProps> = ({
  title,
  hasAddProduct,
  isProductFilter,
  isTransactionFilter,
  isBatchFilter,
  isArchiveFilter,
  productExport,
  batchExport,
  transactionExport,
  hasDateFilter,
}) => {
  const { data: session } = useSession();
  const [showModal, setShowModal] = useState(false);

  const handleTransactionDownload = async () => {
    try {
      const res = await fetch(`/api/transaction/export`);
      if (!res.ok) throw new Error("Failed to fetch transactions");

      const data = await res.json();

      exportTransactionPDF(data);
    } catch (error) {
      console.error("Download failed:", error);
    }
  };

  const router = useRouter();
  const searchParams = useSearchParams();

  const handleDateChange = (range: { from?: Date; to?: Date }) => {
    const params = new URLSearchParams(searchParams.toString());
    if (range.from) params.set("from", format(range.from, "yyyy-MM-dd"));
    else params.delete("from");
    if (range.to) params.set("to", format(range.to, "yyyy-MM-dd"));
    else params.delete("to");
    params.set("page", "1");
    router.push(`?${params.toString()}`);
  };

  const exportTransactionPDF = (transactions: TransactionRow[]) => {
    const doc = new jsPDF();
    const logo = new Image();
    logo.src = "/macoleens_logo.png";

    const userName = session?.user?.username || "Unknown User";
    const today = new Date().toLocaleDateString();

    logo.onload = () => {
      // Center the logo
      const pageWidth = doc.internal.pageSize.getWidth();
      const logoWidth = 25;
      const logoX = (pageWidth - logoWidth) / 2;
      doc.addImage(logo, "PNG", logoX, 10, logoWidth, 40);

      // Title
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text("Transactions Report", pageWidth / 2, 38, { align: "center" });

      // Description
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text(
        "This report summarizes all recorded transactions, including customer details, type, and total amount.",
        pageWidth / 2,
        46,
        { align: "center", maxWidth: 180 }
      );

      // Metadata
      doc.setFontSize(10);
      doc.text(`Generated on: ${today}`, 14, 56);
      doc.text(`Generated by: ${userName}`, 14, 62);

      // Table
      const columns = [
        "ID",
        "Customer",
        "Type",
        "Created At",
        "Quantity",
        "Total",
        "Status",
      ];

      const rows = transactions.map((tx) => [
        tx.id,
        tx.customer,
        tx.source,
        new Date(tx.createdAt).toLocaleDateString(),
        tx.quantity,
        tx.total.toFixed(2),
        tx.status,
      ]);

      autoTable(doc, {
        startY: 70,
        head: [columns],
        body: rows,
      });

      doc.save("transactions.pdf");
    };
  };

  const handleDownload = async (type: string) => {
    try {
      const res = await fetch(`/api/product/export?type=${type}`);
      if (!res.ok) throw new Error("Failed to fetch products");
      const data: ProductRow[] = await res.json();

      if (!data || data.length === 0) {
        setShowModal(true);
        return;
      }

      exportPDF(data, type);
    } catch (error) {
      console.error("Download failed:", error);
    }
  };

  const exportPDF = (data: ProductRow[], type: string) => {
    const doc = new jsPDF();
    const logo = new Image();
    logo.src = "/macoleens_logo.png";

    const userName = session?.user?.username || "Unknown User";
    const today = new Date().toLocaleDateString();

    // Choose brief description based on report type
    const descriptions: Record<string, string> = {
      all: "This report lists all active products with their categories and stock quantities.",
      allBatches:
        "This report shows all active product batches, including release and expiry dates.",
      lowStock:
        "This report lists products with low stock quantities below the threshold.",
      expiring:
        "This report highlights batches nearing expiry within the next 7 days.",
      expired:
        "This report lists all product batches that have already expired.",
    };

    const description =
      descriptions[type] || "This report provides product data.";

    logo.onload = () => {
      // Center the logo
      const pageWidth = doc.internal.pageSize.getWidth();
      const logoWidth = 60;
      const logoX = (pageWidth - logoWidth) / 2;
      doc.addImage(logo, "PNG", logoX, 10, logoWidth, 20);

      // Title
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text(`Products Report - ${type}`, pageWidth / 2, 38, {
        align: "center",
      });

      // Description
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text(description, pageWidth / 2, 46, {
        align: "center",
        maxWidth: 180,
      });

      // Metadata
      doc.text(`Generated on: ${today}`, 14, 56);
      doc.text(`Generated by: ${userName}`, 14, 62);

      let columns: string[] = [];
      let rows: (string | number)[][] = [];

      if (type === "lowStock" || type === "all") {
        columns = ["Product", "Category", "Quantity"];
        rows = data.map((item) => [
          item.product_name,
          item.category?.name || "-",
          item.totalQty ??
            item.batches?.reduce((sum, b) => sum + b.quantity, 0) ??
            0,
        ]);
      } else if (type === "allBatches") {
        columns = [
          "Product",
          "Batch #",
          "Quantity",
          "Release Date",
          "Expiry Date",
        ];
        rows = data.map((item) => [
          item.product?.product_name || "-",
          item.batchNumber ?? "-",
          item.quantity ?? 0,
          item.releaseDate
            ? new Date(item.releaseDate).toLocaleDateString()
            : "-",
          item.expiryDate
            ? new Date(item.expiryDate).toLocaleDateString()
            : "-",
        ]);
      } else {
        columns = ["Product", "Category", "Batch #", "Quantity", "Expiry Date"];
        rows = data.map((item) => [
          item.product?.product_name || item.product_name,
          item.product?.category?.name || "-",
          item.batchNumber ?? "-",
          item.quantity ??
            item.batches?.reduce((sum, b) => sum + b.quantity, 0) ??
            0,
          item.expiryDate
            ? new Date(item.expiryDate).toLocaleDateString()
            : "-",
        ]);
      }

      autoTable(doc, {
        startY: 70,
        head: [columns],
        body: rows,
      });

      doc.save(`products_${type}.pdf`);
    };
  };

  return (
    <div className="mb-4 flex items-center justify-between gap-4">
      <p className="text-2xl font-semibold">{title}</p>

      <div className="w-[30rem] border px-6 rounded-full flex items-center gap-2 bg-gray-50">
        <Search placeholder="Search..." />
      </div>

      {hasDateFilter && <DateRangeFilter onChange={handleDateChange} />}

      <div>
        {isProductFilter ? (
          <ProductFilter />
        ) : isTransactionFilter ? (
          <TransactionFilter />
        ) : isBatchFilter ? (
          <BatchFilter />
        ) : isArchiveFilter ? (
          <ArchiveFilter />
        ) : (
          <AuditFilter />
        )}
      </div>

      {productExport && (
        <>
          {(session?.user.role === "Manager" ||
            session?.user.role === "Pharmacist_Staff") && (
            <div>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="outline">PDF Export</Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent>
                  <DropdownMenuItem onClick={() => handleDownload("all")}>
                    All Products
                  </DropdownMenuItem>

                  <DropdownMenuItem onClick={() => handleDownload("lowStock")}>
                    Low Stock Products
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          )}
        </>
      )}

      {batchExport && (
        <>
          {(session?.user.role === "Manager" ||
            session?.user.role === "Pharmacist_Staff") && (
            <div>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="outline">PDF Export</Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent>
                  <DropdownMenuItem
                    onClick={() => handleDownload("allBatches")}
                  >
                    All Batches
                  </DropdownMenuItem>

                  <DropdownMenuItem onClick={() => handleDownload("expiring")}>
                    Expiring Batches
                  </DropdownMenuItem>
                  <DropdownMenuItem onClick={() => handleDownload("expired")}>
                    Expired Batches
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          )}
        </>
      )}

      {hasAddProduct && (
        <>
          {(session?.user.role === "Manager" ||
            session?.user.role === "Pharmacist_Staff") && (
            <div>
              <AddProductForm />
            </div>
          )}
        </>
      )}
      {transactionExport && (
        <Button variant="outline" onClick={handleTransactionDownload}>
          PDF Export
        </Button>
      )}

      <Dialog open={showModal} onOpenChange={setShowModal}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>No Data Found</DialogTitle>
            <DialogDescription>
              There are no products available for this report.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button onClick={() => setShowModal(false)}>OK</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default PageTableHeader;
