"use client";

import SelectField from "./SelectField";
import { MoreVertical } from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
} from "@/components/ui/dropdown-menu";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { useSession } from "next-auth/react";

type ExportOption = "csv" | "pdf";

interface WidgetHeaderProps {
  filter: string;
  setFilter: (value: string) => void;
  title: string;
  data: { label: string; value: number }[];
  reportType:
    | "type"
    | "sales"
    | "top selling product"
    | "inventory by category"
    | "requested"
    | "order type";
  userName?: string;
}

const WidgetHeader = ({
  filter,
  setFilter,
  title,
  data,
  reportType,
  userName,
}: WidgetHeaderProps) => {
  const { data: session } = useSession();
  const userRole = session?.user.role;

  const handleExport = (format: ExportOption) => {
    if (format === "csv") {
      exportCSV();
    } else {
      exportPDF();
    }
  };

  const getHeaders = () => {
    if (reportType === "type")
      return { headerLabel: "Type", valueLabel: "Revenue" };
    if (reportType === "top selling product")
      return { headerLabel: "Product", valueLabel: "Quantity" };
    if (reportType === "inventory by category") {
      return { headerLabel: "Category", valueLabel: "Item" };
    }
    if (reportType === "requested") {
      return { headerLabel: "Category", valueLabel: "Requested" };
    }
    if (reportType === "order type") {
      return { headerLabel: "Category", valueLabel: "Order Type" };
    }
    return { headerLabel: "Date", valueLabel: "Sales" };
  };

  const exportCSV = () => {
    const { headerLabel, valueLabel } = getHeaders();

    const rows: (string | number)[][] = [
      [`${title} - ${filter}`],
      ["Generated on", new Date().toLocaleDateString()],
      [],
      [headerLabel, valueLabel],
      ...data.map((item) => [item.label, item.value]),
      ["Total", data.reduce((sum, i) => sum + i.value, 0)],
    ];

    const csvContent =
      "data:text/csv;charset=utf-8," +
      rows.map((row) => row.join(",")).join("\n");

    const link = document.createElement("a");
    link.href = encodeURI(csvContent);
    link.download = `${title.replace(/\s+/g, "_").toLowerCase()}_${filter}.csv`;
    link.click();
  };

  const exportPDF = () => {
    const doc = new jsPDF();
    const { headerLabel, valueLabel } = getHeaders();
    const total = data.reduce((sum, i) => sum + i.value, 0);

    const logo = new Image();
    logo.src = "/macoleens_logo.png"; // or your uploaded path

    const reportDescriptions: Record<string, string> = {
      category:
        "This report shows total revenue generated per product category.",
      sales:
        "This report summarizes sales performance within the selected date range.",
      "top selling product":
        "This report lists the highest revenue-generating products.",
      "inventory by category":
        "This report displays current inventory counts grouped by category.",
      requested:
        "This report details the total number of requested items by category.",
      "order type":
        "This report breaks down the number of orders by their order type.",
    };

    const description =
      reportDescriptions[reportType] || "This report provides summarized data.";

    logo.onload = () => {
      // ✅ Centered Logo (auto width adjustment)
      const pageWidth = doc.internal.pageSize.getWidth();
      const logoWidth = 60; // adjust this for desired size
      const logoHeight = 20; // keep proportion
      const xPos = (pageWidth - logoWidth) / 2; // centers the image
      const yPos = 10;

      doc.addImage(logo, "PNG", xPos, yPos, logoWidth, logoHeight);

      // Title below logo
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text(`${title} - ${filter}`, pageWidth / 2, yPos + 30, {
        align: "center",
      });

      // Description below title
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text(description, pageWidth / 2, yPos + 38, {
        align: "center",
        maxWidth: 180,
      });

      // Date
      doc.text(
        `Generated on: ${new Date().toLocaleDateString()}`,
        pageWidth / 2,
        yPos + 46,
        { align: "center" }
      );

      if (userName) {
        doc.text(`Generated by: ${userName}`, pageWidth / 2, yPos + 52, {
          align: "center",
        });
      }

      // Table
      const rows = data.map((item) => [
        item.label,
        `${item.value.toLocaleString()}`,
      ]);
      rows.push(["Total", `${total.toLocaleString()}`]);

      autoTable(doc, {
        startY: yPos + 54,
        head: [[headerLabel, valueLabel]],
        body: rows,
        styles: { halign: "center" },
        headStyles: { fillColor: [41, 128, 185] }, // optional color styling
        didParseCell: (data) => {
          if (data.row.index === rows.length - 1) {
            data.cell.styles.fontStyle = "bold";
          }
        },
      });

      // Footer
      const pageHeight = doc.internal.pageSize.height;
      doc.setFontSize(9);
      doc.text(
        "This report was generated automatically by the Macoleens Management System.",
        pageWidth / 2,
        pageHeight - 10,
        { align: "center" }
      );

      const safeFilter = filter.replace(/\s+/g, "_").toLowerCase();
      doc.save(`${title.replace(/\s+/g, "_").toLowerCase()}_${safeFilter}.pdf`);
    };
  };

  return (
    <div className="flex justify-between mb-2 w-full border-b p-3 px-4 items-center">
      <p className="text-lg font-semibold">{title}</p>

      <div className="flex items-center gap-3">
        <SelectField
          label="Select a range"
          option={[
            { label: "Last 7 Days", value: "Last 7 Days" },
            { label: "This Month", value: "This Month" },
            { label: "This Year", value: "This Year" },
          ]}
          value={filter}
          onChange={(value) => setFilter(value)}
        />
        {(userRole === "Pharmacist_Staff" ||
          userRole === "Manager" ||
          userRole === "Cashier" ||
          userRole === "SuperAdmin") && (
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <button className="p-2 rounded-md hover:bg-gray-100">
                <MoreVertical className="w-5 h-5" />
              </button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuItem onClick={() => handleExport("csv")}>
                Export as CSV
              </DropdownMenuItem>
              <DropdownMenuItem onClick={() => handleExport("pdf")}>
                Export as PDF
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        )}
      </div>
    </div>
  );
};

export default WidgetHeader;
