-- AlterTable
ALTER TABLE `user` ADD COLUMN `isOnline` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `lastSeen` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `status` ENUM('ACTIVE', 'DISABLE') NOT NULL DEFAULT 'ACTIVE';
