import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import { capitalLetter } from "../utils";
import { LastAutoTableShape, logoPath } from "./productReport";

interface AuditLogItem {
  id: number;
  action: string;
  description: string;
  entityType: string;
  entityId: number | null;
  createdAt: Date;
  user: {
    username: string;
  };
}

interface AuditReportMeta {
  dateRange: {
    from: string | null;
    to: string | null;
  };
  searchQuery: string | null;
  actionFilters: string[] | null;
  entityTypeFilters: string[] | null;
  totalLogs: number;
  generatedAt: string;
}

// Action labels for display
const auditActionLabels: Record<string, string> = {
  create: "Create",
  update: "Update",
  delete: "Delete",
  login: "Login",
  logout: "Logout",
  approve: "Approve",
  decline: "Decline",
};

export const generateAuditLogPDF = (
  logs: AuditLogItem[],
  meta: AuditReportMeta,
  generatedBy: string
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // --- Header ---
  const logoWidth = 50;
  const logoHeight = 12;
  doc.addImage(logoPath, "PNG", (pageWidth - logoWidth) / 2, 8, logoWidth, logoHeight);

  doc.setFontSize(14);
  doc.text("Audit Log Report", pageWidth / 2, 30, { align: "center" });

  // Report Info
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  let yPos = 45;

  function addLabelValue(label: string, value: string) {
    doc.setFont("helvetica", "bold");
    doc.text(label, 14, yPos);
    const labelWidth = doc.getTextWidth(label);
    doc.setFont("helvetica", "normal");
    doc.text(value, 14 + labelWidth + 2, yPos);
    yPos += 5;
  }

  if (meta.dateRange.from || meta.dateRange.to) {
    const fromDate = meta.dateRange.from
      ? format(new Date(meta.dateRange.from), "MMM dd, yyyy")
      : "Start";
    const toDate = meta.dateRange.to
      ? format(new Date(meta.dateRange.to), "MMM dd, yyyy")
      : "End";
    addLabelValue("Period:", `${fromDate} - ${toDate}`);
  }

  if (meta.searchQuery) {
    addLabelValue("Search:", meta.searchQuery);
  }

  if (meta.actionFilters && meta.actionFilters.length > 0) {
    const filterLabels = meta.actionFilters
      .map((a) => auditActionLabels[a] || capitalLetter(a))
      .join(", ");
    addLabelValue("Action Filters:", filterLabels);
  }

  if (meta.entityTypeFilters && meta.entityTypeFilters.length > 0) {
    const entityLabels = meta.entityTypeFilters
      .map((e) => capitalLetter(e))
      .join(", ");
    addLabelValue("Entity Type Filters:", entityLabels);
  }

  addLabelValue("Total Logs:", `${meta.totalLogs}`);
  addLabelValue("Generated By:", generatedBy);
  addLabelValue(
    "Generated At:",
    format(new Date(meta.generatedAt), "MMM dd, yyyy hh:mm a")
  );

  yPos += 5;

  // --- Table ---
  const tableData = logs.map((log) => [
    `#${log.id}`,
    auditActionLabels[log.action] || capitalLetter(log.action),
    log.description,
    capitalLetter(log.entityType),
    log.entityId ? `#${log.entityId}` : "N/A",
    log.user?.username || "System",
    format(new Date(log.createdAt), "MMM dd, yyyy hh:mm a"),
  ]);

  autoTable(doc, {
    startY: yPos,
    head: [["Log ID", "Event", "Description", "Target Type", "Target ID", "Performed By", "Timestamp"]],
    body: tableData,
    theme: "grid",
    headStyles: {
      fillColor: [66, 139, 202],
      textColor: 255,
      fontStyle: "bold",
      fontSize: 8,
    },
    bodyStyles: { fontSize: 7 },
    columnStyles: {
      0: { cellWidth: 15 },
      1: { cellWidth: 20 },
      2: { cellWidth: 50 },
      3: { cellWidth: 25 },
      4: { cellWidth: 18 },
      5: { cellWidth: 25 },
      6: { cellWidth: 32 },
    },
    margin: { left: 14, right: 14 },
  });

  // --- Footer ---
  const finalY = ((doc as LastAutoTableShape).lastAutoTable?.finalY || yPos) + 10;

  doc.setFont("helvetica", "italic");
  doc.setFontSize(8);
  doc.text(
    `Total ${meta.totalLogs} audit log entries`,
    pageWidth / 2,
    finalY,
    { align: "center" }
  );

  // --- Save ---
  const fileName = `Audit_Log_Report_${format(new Date(), "yyyyMMdd_HHmmss")}.pdf`;
  doc.save(fileName);
};