import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import { capitalLetter } from "../utils";
import { LastAutoTableShape, logoPath } from "./productReport";

interface MedTechRequestItem {
  productName: string;
  quantity: number;
  price: number;
}

interface MedTechTransaction {
  id: number;
  type: string;
  createdAt: Date;
  updatedAt: Date;
  status: string;
  remarks: string;
  notes: string;
  source: string;
  requestedBy: string;
  receivedBy: string;
  receivedAt: Date | null;
  approvedBy: string;
  approvedAt: Date | null;
  itemDetails: MedTechRequestItem[];
  total: number;
}

interface ReportMeta {
  dateRange: {
    from: string | null;
    to: string | null;
  };
  searchQuery: string | null;
  statusFilters: string[] | null;
  sourceFilters: string[] | null;
  totalTransactions: number;
  totalAmount: number;
  generatedAt: string;
}

// Status and Remarks labels for display
const medTechStatusLabels: Record<string, string> = {
  pending_for_approval: "Pending for Approval",
  approved: "Approved",
  declined: "Declined",
};

const medTechRemarksLabels: Record<string, string> = {
  processing: "Processing",
  ready: "Ready",
  released: "Released",
};

export const generateMedTechTransactionPDF = (
  transactions: MedTechTransaction[],
  meta: ReportMeta,
  generatedBy: string
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // --- Header ---
  const logoWidth = 50;
  const logoHeight = 12;
  doc.addImage(logoPath, "PNG", (pageWidth - logoWidth) / 2, 8, logoWidth, logoHeight);

  doc.setFontSize(14);
  doc.text("MedTech Transaction Report", pageWidth / 2, 30, { align: "center" });

  // Report Info
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  let yPos = 45;

  function addLabelValue(label: string, value: string) {
    doc.setFont("helvetica", "bold");
    doc.text(label, 14, yPos);
    const labelWidth = doc.getTextWidth(label);
    doc.setFont("helvetica", "normal");
    doc.text(value, 14 + labelWidth + 2, yPos);
    yPos += 5;
  }

  if (meta.dateRange.from || meta.dateRange.to) {
    const fromDate = meta.dateRange.from
      ? format(new Date(meta.dateRange.from), "MMM dd, yyyy")
      : "Start";
    const toDate = meta.dateRange.to
      ? format(new Date(meta.dateRange.to), "MMM dd, yyyy")
      : "End";
    addLabelValue("Period:", `${fromDate} - ${toDate}`);
  }

  if (meta.searchQuery) {
    addLabelValue("Search:", `Request ID: ${meta.searchQuery}`);
  }

  if (meta.statusFilters && meta.statusFilters.length > 0) {
    const filterLabels = meta.statusFilters
      .map((s) => medTechStatusLabels[s] || medTechRemarksLabels[s] || capitalLetter(s))
      .join(", ");
    addLabelValue("Filters:", filterLabels);
  }

  addLabelValue("Total Transactions:", `${meta.totalTransactions}`);
  addLabelValue("Total Amount:", `PHP ${meta.totalAmount.toFixed(2)}`);
  addLabelValue("Generated By:", generatedBy);
  addLabelValue(
    "Generated At:",
    format(new Date(meta.generatedAt), "MMM dd, yyyy hh:mm a")
  );

  yPos += 5;

  // --- Table ---
  const tableData = transactions.map((tx) => [
    `#${tx.id}`,
    format(new Date(tx.createdAt), "MMM dd, yyyy hh:mm a"),
    medTechStatusLabels[tx.status] || tx.status,
    medTechRemarksLabels[tx.remarks] || tx.remarks,
    tx.requestedBy,
    tx.receivedBy,
    tx.approvedBy,
    `${tx.total.toFixed(2)}`,
  ]);

  autoTable(doc, {
    startY: yPos,
    head: [["ID", "Date", "Status", "Remarks", "Requested By", "Received By", "Approved By", "Total (PHP)"]],
    body: tableData,
    theme: "grid",
    headStyles: {
      fillColor: [66, 139, 202],
      textColor: 255,
      fontStyle: "bold",
      fontSize: 8,
    },
    bodyStyles: { fontSize: 7 },
    columnStyles: {
      0: { cellWidth: 12 },
      1: { cellWidth: 30 },
      2: { cellWidth: 22 },
      3: { cellWidth: 18 },
      4: { cellWidth: 25 },
      5: { cellWidth: 25 },
      6: { cellWidth: 25 },
      8: { cellWidth: 18 },
    },
    margin: { left: 14, right: 14 },
  });

  // --- Total below table ---
  const finalY = ((doc as LastAutoTableShape).lastAutoTable?.finalY || yPos) + 10;

  doc.setFont("helvetica", "bold");
  doc.text("Total Amount:", pageWidth - 70, finalY);
  doc.setFont("helvetica", "normal");
  doc.text(`PHP ${meta.totalAmount.toFixed(2)}`, pageWidth - 25, finalY, { align: "right" });

  // --- Save ---
  const fileName = `MedTech_Transaction_Report_${format(new Date(), "yyyyMMdd_HHmmss")}.pdf`;
  doc.save(fileName);
};