import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import { LastAutoTableShape, logoPath } from "./productReport";

const formatManila = (isoOrDate: string | Date) => {
  const date = typeof isoOrDate === 'string' ? new Date(isoOrDate) : isoOrDate;
  return format(date, "MMM dd, yyyy hh:mm a");
};

const formatDateOnly = (dateStr: string) => {
  // Parse YYYY-MM-DD as local date
  const [year, month, day] = dateStr.split('-').map(Number);
  const date = new Date(year, month - 1, day);
  return format(date, "MMM dd, yyyy");
};

export interface SaleItem {
  productName: string;
  category: string;
  quantity: number;
  total: number;
  price?: number;
  productId?: number;
}

interface SaleRecord {
  id: number | string;
  type: "Order Request" | "Walk-In" | string;
  createdAt: string | Date;
  user?: {
    id: number | string;
    name: string;
  } | null;
  items: SaleItem[];
}

interface SalesMeta {
  from?: string | null;
  to?: string | null;
  type: string;
}


export const generateSalesPDF = (
  sales: SaleRecord[],
  meta: SalesMeta,
  generatedBy?: string
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const logoWidth = 45;
  const logoHeight = 10;
  doc.addImage(logoPath, "PNG", (pageWidth / 2) - (logoWidth / 2), 8, logoWidth, logoHeight);

  // === HEADER ===
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Sales Report", pageWidth / 2, 30, { align: "center" });

  // Metadata section
  doc.setFontSize(9);
  let y = 40;
  const leftMargin = 14;

  // Date Range
  if (meta.from || meta.to) {
    doc.setFont("helvetica", "bold");
    doc.text("Date Range:", leftMargin, y);
    doc.setFont("helvetica", "normal");
    const fromText = meta.from ? formatDateOnly(meta.from) : "—";
    const toText = meta.to ? formatDateOnly(meta.to) : "—";
    doc.text(`${fromText} — ${toText}`, leftMargin + 25, y);
    y += 5;
  }

  // Type
  doc.setFont("helvetica", "bold");
  doc.text("Type:", leftMargin, y);
  doc.setFont("helvetica", "normal");
  const typeDisplay = 
    meta.type === "all" ? "All Sales" :
    meta.type === "orderrequest" ? "Order Request" :
    meta.type === "walkin" ? "Walk-In" :
    meta.type;
  doc.text(typeDisplay, leftMargin + 25, y);
  y += 5;

  // Generated By
  if (generatedBy) {
    doc.setFont("helvetica", "bold");
    doc.text("Generated By:", leftMargin, y);
    doc.setFont("helvetica", "normal");
    doc.text(generatedBy, leftMargin + 25, y);
    y += 5;
  }

  // Generated At
  doc.setFont("helvetica", "bold");
  doc.text("Generated At:", leftMargin, y);
  doc.setFont("helvetica", "normal");
  doc.text(formatManila(new Date()), leftMargin + 25, y);

  const startY = y + 7;

  // === BUILD ROWS ===
  const allItems = sales.flatMap((sale) =>
    sale.items.map((item: SaleItem) => ({
      type: sale.type,
      id: sale.id,
      productName: item.productName,
      category: item.category ?? "Uncategorized",
      quantity: item.quantity,
      total: item.total ?? 0,
      createdAt: sale.createdAt,
    }))
  );

  const rows = allItems.map((item) => [
    item.type,
    String(item.id),
    item.productName,
    item.category,
    String(item.quantity),
    item.total ? item.total.toFixed(2) : "—",
    formatManila(item.createdAt),
  ]);

  // === TABLE ===
  autoTable(doc, {
    head: [["Type", "Order ID", "Product", "Category", "Qty", "Total (PHP)", "Date"]],
    body: rows,
    startY,
    margin: { left: leftMargin, right: 14 },
    styles: { fontSize: 8 },
    headStyles: { fillColor: [59, 130, 246], textColor: 255 },
  });

  // === TOTAL ===
  const total = allItems.reduce((sum, item) => sum + (Number(item.total) || 0), 0);
  const finalY = (doc as LastAutoTableShape).lastAutoTable?.finalY ?? startY + 10;

  doc.setFont("helvetica", "bold");
  doc.text(
    `Total Sales: PHP ${total.toLocaleString("en-PH", {
      minimumFractionDigits: 2,
    })}`,
    leftMargin,
    finalY + 8
  );

  // === SAVE ===
  const fromDate = meta.from ? formatDateOnly(meta.from).replace(/[\s,]/g, '-') : 'all';
  const toDate = meta.to ? formatDateOnly(meta.to).replace(/[\s,]/g, '-') : 'all';
  doc.save(`sales-report-${meta.type}-${fromDate}-to-${toDate}.pdf`);
};