import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import { TransactionItem } from "@/app/api/report/transaction/route";
import { LastAutoTableShape } from "./productReport";

export interface Transaction {
  id: number;
  type: string;
  status: string;
  createdAt: Date | string;
  patient_name?: string | null;
  customer_name?: string | null;
  items: TransactionItem[];
}

interface TransactionReportData {
  transactions: Transaction[];
  meta: {
    type: string;
    filter: string;
    filterDisplay: string;
    query: string;
    counts: {
      orderRequests: number;
      walkInTransactions: number;
      total: number;
    };
    grandTotal: number;
  };
}

export const generateTransactionPDF = (
  data: TransactionReportData,
  username: string
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  let yPos = 20;

  // Header
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Transaction Report", pageWidth / 2, yPos, { align: "center" });
  yPos += 10;

  // Report Info
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");

  const typeText =
    data.meta.type === "all"
      ? "All Transactions"
      : data.meta.type === "orderrequest"
      ? "Order Requests Only"
      : "Walk-In Only";

  const filterText = data.meta.filterDisplay || "All";

  doc.text(`Type: ${typeText}`, 14, yPos);
  yPos += 5;
  doc.text(`Filter: ${filterText}`, 14, yPos);
  yPos += 5;
  if (data.meta.query) {
    doc.text(`Search: ${data.meta.query}`, 14, yPos);
    yPos += 5;
  }
  doc.text(`Generated by: ${username}`, 14, yPos);
  yPos += 5;
  doc.text(
    `Generated on: ${format(new Date(), "MMM dd, yyyy hh:mm a")}`,
    14,
    yPos
  );
  yPos += 10;

  // Summary Box
  doc.setDrawColor(200);
  doc.setFillColor(245, 245, 245);
  doc.roundedRect(14, yPos, pageWidth - 28, 20, 2, 2, "FD");

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("Summary", 18, yPos + 6);

  doc.setFont("helvetica", "normal");
  doc.text(
    `Order Requests: ${data.meta.counts.orderRequests}`,
    18,
    yPos + 12
  );
  doc.text(
    `Walk-In Transactions: ${data.meta.counts.walkInTransactions}`,
    100,
    yPos + 12
  );

  doc.setFont("helvetica", "bold");
  doc.text(
    `Total: ₱${data.meta.grandTotal.toFixed(2)}`,
    pageWidth - 18,
    yPos + 12,
    { align: "right" }
  );

  yPos += 25;

  // Build table rows
  const rows = data.transactions.flatMap((txn) =>
    txn.items.map((item: TransactionItem, idx: number) => [
      idx === 0 ? `#${txn.id}` : "",
      idx === 0 ? txn.type : "",
      idx === 0
        ? txn.patient_name || txn.customer_name || "-"
        : "",
      item.productName,
      item.quantity,
      `₱${Number(item.price).toFixed(2)}`,
      `₱${Number(item.total).toFixed(2)}`,
      idx === 0
        ? txn.status.charAt(0).toUpperCase() +
          txn.status.slice(1).replace("_", " ")
        : "",
      idx === 0 ? format(new Date(txn.createdAt), "MMM dd, yyyy") : "",
    ])
  );

  // Table
  autoTable(doc, {
    startY: yPos,
    head: [
      [
        "ID",
        "Type",
        "Customer/Patient",
        "Product",
        "Qty",
        "Price",
        "Total",
        "Status",
        "Date",
      ],
    ],
    body: rows,
    theme: "striped",
    headStyles: { fillColor: [59, 130, 246], fontSize: 8 },
    styles: { fontSize: 7, cellPadding: 1.5 },
    columnStyles: {
      0: { cellWidth: 15 },
      1: { cellWidth: 25 },
      2: { cellWidth: 30 },
      3: { cellWidth: 35 },
      4: { cellWidth: 12, halign: "center" },
      5: { cellWidth: 20, halign: "right" },
      6: { cellWidth: 20, halign: "right" },
      7: { cellWidth: 22 },
      8: { cellWidth: 22 },
    },
  });

  // Footer with Grand Total
  const finalY = (doc as LastAutoTableShape).lastAutoTable?.finalY || yPos;
  let footerY = finalY + 5;

  if (footerY > 250) {
    doc.addPage();
    footerY = 20;
  }

  doc.setDrawColor(59, 130, 246);
  doc.setLineWidth(0.5);
  doc.line(14, footerY, pageWidth - 14, footerY);
  footerY += 7;

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(
    `Grand Total: ₱${data.meta.grandTotal.toFixed(2)}`,
    pageWidth - 14,
    footerY,
    { align: "right" }
  );

  // Save PDF
  const fileName = `Transaction_Report_${format(
    new Date(),
    "yyyyMMdd_HHmmss"
  )}.pdf`;
  doc.save(fileName);
};