import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import { capitalLetter, statusLabels } from "../utils";
import { LastAutoTableShape, logoPath } from "./productReport";

interface TransactionItem {
  productName: string;
  quantity: number;
  price: number;
}

interface Transaction {
  id: number;
  customer: string;
  patient_name?: string;
  roomNumber?: number;
  type: string;
  createdAt: Date;
  source: "Walk In" | "Request Order";
  total: number;
  requestedBy?: string;
  receivedBy?: string;
  processedBy?: string;
  handledBy?: string;
  status: string;
  itemDetails: TransactionItem[];
}

interface ReportMeta {
  dateRange: {
    from: string | null;
    to: string | null;
  };
  searchQuery: string | null;
  statusFilters: string[] | null;
  sourceFilters: string[] | null;
  totalTransactions: number;
  totalAmount: number;
  generatedAt: string;
}

export const generateTransactionPDF = (
  transactions: Transaction[],
  meta: ReportMeta,
  generatedBy: string
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // --- Header ---
  const logoWidth = 50;
  const logoHeight = 12;
  doc.addImage(logoPath, "PNG", (pageWidth - logoWidth) / 2, 8, logoWidth, logoHeight);

  doc.setFontSize(14);
  doc.text("Transaction Report", pageWidth / 2, 30, { align: "center" });

  // Report Info
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  let yPos = 45;

  function addLabelValue(label: string, value: string) {
    doc.setFont("helvetica", "bold");
    doc.text(label, 14, yPos);
    const labelWidth = doc.getTextWidth(label);
    doc.setFont("helvetica", "normal");
    doc.text(value, 14 + labelWidth + 2, yPos);
    yPos += 5;
  }

  if (meta.dateRange.from || meta.dateRange.to) {
    const fromDate = meta.dateRange.from
      ? format(new Date(meta.dateRange.from), "MMM dd, yyyy")
      : "Start";
    const toDate = meta.dateRange.to
      ? format(new Date(meta.dateRange.to), "MMM dd, yyyy")
      : "End";
    addLabelValue("Period:", `${fromDate} - ${toDate}`);
  }

  if (meta.searchQuery) {
    addLabelValue("Search:", meta.searchQuery);
  }

  if (meta.statusFilters && meta.statusFilters.length > 0) {
    const statusLabelsText = meta.statusFilters
      .map((s) => statusLabels[s] || capitalLetter(s))
      .join(", ");
    addLabelValue("Status Filters:", statusLabelsText);
  }

  if (meta.sourceFilters && meta.sourceFilters.length > 0) {
    const sourceLabelsText = meta.sourceFilters
      .map((s) => s === "order_request" ? "Order Request" : "Walk In")
      .join(", ");
    addLabelValue("Source Filters:", sourceLabelsText);
  }

  addLabelValue("Total Transactions:", `${meta.totalTransactions}`);
  addLabelValue("Total Amount:", `PHP ${meta.totalAmount.toFixed(2)}`);
  addLabelValue("Generated By:", generatedBy);
  addLabelValue(
    "Generated At:",
    format(new Date(meta.generatedAt), "MMM dd, yyyy hh:mm a")
  );

  yPos += 5;

  // --- Table ---
  const tableData = transactions.map((tx) => [
    format(new Date(tx.createdAt), "MMM dd, yyyy hh:mm a"),
    tx.source === "Walk In" ? tx.customer : tx.patient_name || tx.customer,
    tx.source === "Request Order" && tx.roomNumber ? `Room ${tx.roomNumber}` : "-",
    capitalLetter(tx.type),
    tx.source,
    statusLabels[tx.status] || tx.status,
    `${tx.total.toFixed(2)}`,
  ]);

  autoTable(doc, {
    startY: yPos,
    head: [["Date", "Customer/Patient", "Room", "Type", "Source", "Status", "Total (PHP)"]],
    body: tableData,
    theme: "grid",
    headStyles: {
      fillColor: [66, 139, 202],
      textColor: 255,
      fontStyle: "bold",
      fontSize: 9,
    },
    bodyStyles: { fontSize: 8 },
    columnStyles: {
      0: { cellWidth: 35 },
      1: { cellWidth: 30 },
      2: { cellWidth: 20 },
      3: { cellWidth: 20 },
      4: { cellWidth: 25 },
      5: { cellWidth: 30 },
      6: { cellWidth: 25 },
    },
    margin: { left: 14, right: 14 },
  });

  // --- Total below table ---
  const finalY = ((doc as LastAutoTableShape).lastAutoTable?.finalY || yPos) + 10;

  doc.setFont("helvetica", "bold");
  doc.text("Total Amount:", pageWidth - 70, finalY);
  doc.setFont("helvetica", "normal");
  doc.text(`PHP ${meta.totalAmount.toFixed(2)}`, pageWidth - 25, finalY, { align: "right" });

  // --- Save ---
  const fileName = `Transaction_Report_${format(new Date(), "yyyyMMdd_HHmmss")}.pdf`;
  doc.save(fileName);
};